site_name: Maksudul Haque's Blog
site_url: https://saadmk11.github.io/blog/
docs_dir: blog

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  icon:
    logo: fontawesome/solid/book
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags:
      tags_file: tags.md
  - search
  - macros
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-MZDZ15E66V
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/saad_mk11
    - icon: fontawesome/brands/github
      link: https://github.com/saadmk11
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/saadmk11/
    - icon: fontawesome/solid/globe
      link: https://saadmk11.github.io
    - icon: fontawesome/brands/dev
      link: https://dev.to/saadmk11
