site_name: Maksudul Haque's Blog
docs_dir: blog
theme:
  name: material
  features:
#    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
  icon:
    logo: fontawesome/solid/book
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags:
      tags_file: tags.md
  - search
  - macros
